# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39

install:
  - python3 -m pip install -U tox setuptools wheel
  - python3 -m pip install -Ue .[tests]

build: off # Not a C# project, build stuff at the test step instead.

test_script:
  - tox

after_test:
  - python3 setup.py sdist bdist_wheel
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
